# Generated by Django 4.0.3 on 2022-04-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='nsu_id',
            field=models.CharField(default='', max_length=30, verbose_name='nsu_id'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='', max_length=50, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='', max_length=12, verbose_name='role'),
        ),
    ]
