# Generated by Django 4.0.4 on 2022-04-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='reply',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='complain',
            name='role',
            field=models.CharField(default='', max_length=10),
        ),
    ]
